### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sympmarc**
Minor grammar fixes.

Also, is this still true? "Despite being ReactJS exclusive,..."

Nort sure what this sentence means: "HTML/CSS documented components serve no other longevity than any other framework."

### CODE REVIEW

**Comment by juliemturner** [comment]
Yes, still only ReactJS...  I can't say that I understand that sentence either... @StfBauer ??  Otherwise this could be merged.

**Comment by sympmarc** [comment]
I asked about the ReactJS line because further down you give links to an Angular example. At the very least, I find it confusing.

**Comment by juliemturner** [comment]
I think someone started Angular but then it didn't go anywhere, so yeah that needs to be amended... @StfBauer do you know the status of the Angular initiative...

**Comment by StfBauer** [comment]
Thank you, @sympmarc for the updates.

**Pull request merged**
